dir: "{{ .InterfaceDir }}"
filename: "mock_{{ .InterfaceNameSnake }}.go"
with-expecter: false
inpackage: true
packages:
  github.com/G-Research/fasttrackml/pkg/api/mlflow/dao/repositories:
    interfaces:
      BaseRepositoryProvider:
      ExperimentRepositoryProvider:
      MetricRepositoryProvider:
      NamespaceRepositoryProvider:
      ParamRepositoryProvider:
      RunRepositoryProvider:
      TagRepositoryProvider:
      LogRepositoryProvider:
      ArtifactRepositoryProvider:
  github.com/G-Research/fasttrackml/pkg/api/mlflow/services/artifact/storage:
    interfaces:
      ArtifactStorageFactoryProvider:
      ArtifactStorageProvider:
