name: AWS-Release

on:
  push:


jobs:
  aws-release:
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull gresearch/fasttrackml:latest
      - name: Delete old container
        run: docker rm -f go-app-container
      - name: Run docker container go-app-container
        run: docker run -d -p 80:5000 --name go-app-container gresearch/fasttrackml
    
